CREATE DATABASE IF NOT EXISTS geomardy CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE geomardy;
CREATE TABLE contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  org VARCHAR(255),
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  project_type VARCHAR(150),
  message TEXT,
  filename VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
